### ISSUE TITLE
Input Arguments

### ISSUE THREAD

**Issue by nermish** [Calamitizer/WildbowCrawler#1]
inputting: python crawler.py worm single '#A' '#C'
error:
 File "crawler.py", line 46
    print 'Wrong number of input arguments.'
                                           ^
SyntaxError: Missing parentheses in call to 'print'

is the 'README' incorrect?

**Comment by I3olle** [comment]
I am getting different outputs depending on python2 adn python3

```
python3 crawler.py pact single '#A' '#C'
  File "crawler.py", line 46
    print 'Wrong number of input arguments.'
                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Wrong number of input arguments.')?
```

```
python2 crawler.py pact single '#A' '#C'
path: ''
Accessing URL ...
Traceback (most recent call last):
  File "crawler.py", line 252, in <module>
    crawler.run()
  File "crawler.py", line 131, in run
    self.get_soup()
  File "crawler.py", line 139, in get_soup
    res = requests.get(self.url)
  File "/Users/pjost/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/pjost/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/pjost/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/Users/pjost/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/pjost/Library/Python/2.7/lib/python/site-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/Users/pjost/Library/Python/2.7/lib/python/site-packages/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```

So I guessed the syntax must be python2

Checking the code I found this:
```
        self.urls = {
            'Worm': 'http://parahumans.wordpress.com/category/stories-arcs-1-10/arc-1-gestation/1-01/',
            'Pact': '',
            'Twig': '',
        }
```
Meaning there is no URL provided for anything but worm.

So I added some already used by https://github.com/nicohman/rust-wildbow-scraper:
```
 self.urls = {
            'Worm': 'http://parahumans.wordpress.com/category/stories-arcs-1-10/arc-1-gestation/1-01/',
            'Pact': 'http://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-01/',
            'Twig': 'http://twigserial.wordpress.com/2014/12/24/taking-root-1-1/',
        }
```

Still getting these errors though:
```
python2 crawler.py twig single '#A' '#C'
path: ''
Accessing URL http://twigserial.wordpress.com/2014/12/24/taking-root-1-1/...
Got title: Taking Root 1.1
Reached new arc "Taking Root"
Delimiter problem: 0
Aborting.
```

```
python2 crawler.py pact single '#A' '#C'
path: ''
Accessing URL http://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-01/...
Traceback (most recent call last):
  File "crawler.py", line 252, in <module>
    crawler.run()
  File "crawler.py", line 132, in run
    self.parse()
  File "crawler.py", line 144, in parse
    self.get_title()
  File "crawler.py", line 153, in get_title
    self.title = self.format_string(match.string)
  File "crawler.py", line 211, in format_string
    return self.reppattern.sub(lambda match: self.reps[re.escape(match.group(0))], string)
TypeError: expected string or buffer
```

Which is when I stopped debugging
